import { defineNuxtConfig } from "nuxt/config";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const gaId = "G-VGSV4M0LY9";

// Every page path, generated by scripts/build-icon-data.mjs (missing during `nuxt prepare`).
const routesFile = fileURLToPath(new URL("./app/generated/routes.json", import.meta.url));
const routes = existsSync(routesFile) ? JSON.parse(readFileSync(routesFile, "utf8")) : ["/"];

export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  ssr: true,
  modules: ["@nuxtjs/tailwindcss", "@nuxtjs/color-mode"],
  css: ["~/assets/css/styles.css"],
  colorMode: {
    classSuffix: "",
  },
  app: {
    head: {
      htmlAttrs: { lang: "en" },
      title: "Fluenticons",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        { "http-equiv": "Content-Security-Policy", content: "upgrade-insecure-requests" },
        { name: "theme-color", content: "#ffffff" },
        { property: "og:site_name", content: "Fluenticons" },
      ],
      link: [
        { rel: "icon", type: "image/x-icon", href: "/favicon.ico" },
        { rel: "apple-touch-icon", href: "/icon.png" },
        { rel: "manifest", href: "/manifest.webmanifest" },
        { rel: "alternate", type: "application/rss+xml", title: "New Fluent icons", href: "/feed.xml" },
      ],
      script: [
        { src: `https://www.googletagmanager.com/gtag/js?id=${gaId}`, async: true },
        {
          innerHTML: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${gaId}');`,
        },
      ],
    },
  },
  experimental: {
    appManifest: false,
  },
  // Every page is prerendered. Without the app manifest, this rule is how the
  // client knows to load a page's prerendered data (_payload.json) when
  // navigating within the site.
  routeRules: {
    "/**": { prerender: true },
  },
  nitro: {
    // Plain static output; public/_headers and public/_redirects are the
    // only Cloudflare Pages rules (no auto-generated catch-all fallback).
    preset: "static",
    output: { publicDir: "dist" },
    publicAssets: [
      { dir: fileURLToPath(new URL("./app/generated/public", import.meta.url)), maxAge: 0 },
    ],
    prerender: {
      routes,
      crawlLinks: false,
      failOnError: true,
    },
  },
});
