import { defineNuxtConfig } from "nuxt/config";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// This is fluenticons.co's config, and also the base layer of the Material
// Icons site (sites/material), which sets ICON_SITE=material before loading
// it. Everything specific to fluenticons.co applies only when building it.
const fluent = process.env.ICON_SITE !== "material";
const local = (path) => fileURLToPath(new URL(path, import.meta.url));

const gaId = "G-VGSV4M0LY9";

// The sponsor (app/sponsor.ts) is checked when the site is built: a bad tagline,
// link, logo or date stops the build instead of reaching the live site. The
// logo file to use (.svg, else .png) is picked here and passed in app config.
let sponsorLogo = "";
if (fluent) {
  const { default: sponsor } = await import("./app/sponsor.ts");
  const utils = await import("./app/utils/sponsor.ts");
  const exists = (path) => existsSync(local(`./public${path}`));
  const problems = utils.sponsorProblems(sponsor, exists);
  if (problems.length) throw new Error(`app/sponsor.ts: ${problems.join("; ")}`);
  sponsorLogo = utils.sponsorLogo(sponsor, exists);
}

// Every page path, generated by scripts/build-icon-data.mjs (missing during `nuxt prepare`).
const routesFile = local("./app/generated/routes.json");
const routes = !fluent ? [] : existsSync(routesFile) ? JSON.parse(readFileSync(routesFile, "utf8")) : ["/"];

export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  ssr: true,
  modules: ["@nuxtjs/tailwindcss", "@nuxtjs/color-mode"],
  appConfig: { sponsorLogo },
  css: [local("./app/assets/css/styles.css")],
  // As a layer, this site's public/ (6,000+ Fluent icons) must not be copied.
  ...(!fluent && { dir: { public: "public-fluent-only" } }),
  colorMode: {
    classSuffix: "",
  },
  app: fluent
    ? {
        head: {
          htmlAttrs: { lang: "en" },
          title: "Fluenticons",
          meta: [
            { charset: "utf-8" },
            { name: "viewport", content: "width=device-width, initial-scale=1" },
            { "http-equiv": "Content-Security-Policy", content: "upgrade-insecure-requests" },
            { name: "theme-color", content: "#ffffff" },
            { property: "og:site_name", content: "Fluenticons" },
          ],
          link: [
            { rel: "icon", type: "image/x-icon", href: "/favicon.ico" },
            { rel: "apple-touch-icon", href: "/icon.png" },
            { rel: "manifest", href: "/manifest.webmanifest" },
            { rel: "alternate", type: "application/rss+xml", title: "New Fluent icons", href: "/feed.xml" },
          ],
          script: [
            { src: `https://www.googletagmanager.com/gtag/js?id=${gaId}`, async: true },
            {
              innerHTML: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${gaId}');`,
            },
          ],
        },
      }
    : {},
  experimental: {
    appManifest: false,
  },
  // Every page is prerendered. Without the app manifest, this rule is how the
  // client knows to load a page's prerendered data (_payload.json) when
  // navigating within the site.
  routeRules: {
    "/**": { prerender: true },
  },
  nitro: {
    // Plain static output; public/_headers and public/_redirects are the
    // only Cloudflare Pages rules (no auto-generated catch-all fallback).
    preset: "static",
    ...(fluent && {
      output: { publicDir: "dist" },
      publicAssets: [{ dir: local("./app/generated/public"), maxAge: 0 }],
    }),
    prerender: {
      routes,
      crawlLinks: false,
      failOnError: true,
    },
  },
});
