import { defineNuxtConfig } from "nuxt/config";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// materialicons.co: the fluenticons.co app (the repo root) as a base layer,
// with this site's data, icons, content and pages. Set before the root
// config loads, so it leaves out everything specific to fluenticons.co.
process.env.ICON_SITE = "material";

const local = (path) => fileURLToPath(new URL(path, import.meta.url));
const gaId = "G-EN85Z8G3Z6"; // Material Icons web stream (separate from fluenticons.co)

// Every page path, generated by `node scripts/build-icon-data.mjs sites/material`.
const routesFile = local("./app/generated/routes.json");
const routes = existsSync(routesFile) ? JSON.parse(readFileSync(routesFile, "utf8")) : ["/"];

// Pages of the base layer that this site doesn't have.
const FLUENT_ONLY = new Set(["/outlined", "/color", "/ai", "/sponsor"]);

export default defineNuxtConfig({
  extends: [local("../../")],
  // "~" in the shared code means this site's app/ (its generated data and
  // site.js), not the base layer's.
  experimental: { localLayerAliases: false },
  dir: { public: "public" },
  app: {
    head: {
      htmlAttrs: { lang: "en" },
      title: "Materialicons",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        { "http-equiv": "Content-Security-Policy", content: "upgrade-insecure-requests" },
        { name: "theme-color", content: "#ffffff" },
        { property: "og:site_name", content: "Materialicons" },
      ],
      link: [
        { rel: "icon", type: "image/x-icon", href: "/favicon.ico" },
        { rel: "apple-touch-icon", href: "/icon.png" },
        { rel: "manifest", href: "/manifest.webmanifest" },
        { rel: "alternate", type: "application/rss+xml", title: "New Material icons", href: "/feed.xml" },
      ],
      script: [
        // Fallback for www.materialicons.co: send visitors to the same page on
        // https://materialicons.co. (The 301 itself is a Cloudflare Redirect Rule.)
        {
          innerHTML: `if(location.hostname==="www.materialicons.co")location.replace("https://materialicons.co"+location.pathname+location.search+location.hash);`,
        },
        { src: `https://www.googletagmanager.com/gtag/js?id=${gaId}`, async: true },
        {
          innerHTML: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${gaId}');`,
        },
      ],
    },
  },
  hooks: {
    "pages:extend"(pages) {
      for (let i = pages.length - 1; i >= 0; i--) {
        if (FLUENT_ONLY.has(pages[i].path)) pages.splice(i, 1);
        else if (pages[i].children) {
          pages[i].children = pages[i].children.filter((c) => !FLUENT_ONLY.has(`/${c.path}`.replace(/^\/+/, "/")));
        }
      }
    },
  },
  nitro: {
    output: { publicDir: local("./dist") },
    publicAssets: [{ dir: local("./app/generated/public"), maxAge: 0 }],
    prerender: { routes },
  },
});
