// What people (and coding agents) call a UI concept, mapped to the words
// Microsoft uses in Fluent icon names and keywords. Keys and values are
// singular and lower case. Search matches the words themselves first; these
// only add candidates, at a lower weight (see agent/search.js).
//
// Add entries when real searches come back empty or wrong (see README,
// "Agent API"). Values must be words that appear in icon names or keywords.
export default {
  // People and accounts
  user: ["person", "people", "account", "contact", "guest"],
  users: ["people", "person", "team"],
  member: ["person", "people", "team"],
  account: ["person", "account"],
  profile: ["person", "contact", "card"],
  customer: ["person", "people", "contact"],
  client: ["person", "people", "briefcase"],
  team: ["people", "team", "community"],
  group: ["people", "team", "community"],
  avatar: ["person", "emoji"],
  admin: ["shield", "person", "key", "settings"],
  role: ["person", "badge", "shield"],
  employee: ["person", "badge", "briefcase"],
  // Security
  permission: ["lock", "key", "shield", "access"],
  security: ["shield", "lock", "key"],
  secure: ["shield", "lock"],
  privacy: ["shield", "lock", "eye", "off"],
  auth: ["key", "lock", "person", "password"],
  authentication: ["key", "lock", "password", "fingerprint"],
  login: ["person", "key", "arrow", "enter", "door"],
  signin: ["person", "key", "arrow", "enter", "door"],
  logout: ["sign", "out", "arrow", "exit", "door"],
  signout: ["sign", "out", "arrow", "exit", "door"],
  password: ["password", "key", "lock"],
  access: ["key", "lock", "shield", "access"],
  verified: ["checkmark", "shield", "badge", "certificate"],
  verify: ["checkmark", "shield"],
  unlock: ["lock", "open", "key"],
  encryption: ["lock", "key", "shield"],
  // Money
  billing: ["payment", "receipt", "money", "wallet", "card", "credit"],
  bill: ["receipt", "payment", "money"],
  invoice: ["receipt", "document", "money"],
  payment: ["payment", "wallet", "card", "money", "credit"],
  pay: ["payment", "wallet", "money"],
  subscription: ["payment", "receipt", "arrow", "repeat", "premium"],
  price: ["tag", "money", "receipt", "currency"],
  pricing: ["tag", "money", "currency"],
  cost: ["money", "currency", "receipt"],
  finance: ["money", "bank", "wallet", "currency", "chart"],
  financial: ["money", "bank", "currency"],
  checkout: ["cart", "payment", "shopping", "bag"],
  cart: ["cart", "shopping", "bag"],
  shop: ["shopping", "bag", "cart", "store", "retail"],
  store: ["store", "shopping", "building", "retail"],
  purchase: ["shopping", "cart", "payment", "bag"],
  order: ["shopping", "bag", "receipt", "box"],
  revenue: ["money", "chart", "trending", "arrow"],
  cash: ["money", "wallet", "coin"],
  dollar: ["money", "currency", "dollar"],
  bank: ["bank", "building", "money"],
  tax: ["receipt", "calculator", "money"],
  // Navigation and app areas
  dashboard: ["board", "grid", "layout", "gauge", "data"],
  overview: ["board", "grid", "layout"],
  home: ["home", "house"],
  house: ["home"],
  main: ["home"],
  project: ["folder", "briefcase", "board", "clipboard", "task"],
  workspace: ["board", "desktop", "window"],
  portfolio: ["briefcase", "folder"],
  task: ["task", "checkmark", "clipboard", "list"],
  todo: ["task", "checkmark", "checkbox", "list"],
  menu: ["navigation", "line", "horizontal"],
  hamburger: ["navigation", "line", "horizontal"],
  sidebar: ["panel", "sidebar", "left"],
  navigation: ["navigation", "arrow", "compass"],
  back: ["arrow", "left", "back"],
  forward: ["arrow", "right", "forward"],
  next: ["arrow", "right", "next", "chevron"],
  previous: ["arrow", "left", "previous", "chevron"],
  expand: ["chevron", "down", "expand"],
  collapse: ["chevron", "up", "collapse"],
  dropdown: ["chevron", "down", "caret"],
  close: ["dismiss", "close"],
  cancel: ["dismiss", "prohibited"],
  exit: ["dismiss", "sign", "out", "door"],
  more: ["more", "horizontal", "vertical", "dot"],
  option: ["more", "settings", "options"],
  overflow: ["more", "horizontal"],
  // Settings and tools
  setting: ["settings", "gear", "options", "wrench"],
  settings: ["settings", "gear", "options"],
  preference: ["settings", "options", "toggle"],
  config: ["settings", "wrench", "options"],
  configuration: ["settings", "wrench"],
  gear: ["settings"],
  cog: ["settings"],
  tool: ["toolbox", "wrench", "tool"],
  customize: ["paint", "brush", "settings", "options"],
  theme: ["paint", "color", "dark", "theme"],
  // Data
  analytics: ["data", "chart", "trending", "pie", "bar", "poll"],
  analytic: ["data", "chart", "trending", "pie", "bar"],
  metric: ["data", "chart", "gauge", "trending"],
  stat: ["data", "chart", "bar", "poll"],
  statistic: ["data", "chart", "bar", "poll"],
  report: ["document", "data", "chart", "clipboard"],
  reporting: ["data", "chart", "document"],
  chart: ["chart", "data", "pie", "bar", "line"],
  graph: ["chart", "data", "line", "trending"],
  performance: ["gauge", "trending", "data", "pulse"],
  growth: ["trending", "arrow", "growth"],
  insight: ["lightbulb", "data", "sparkle"],
  kpi: ["gauge", "data", "target"],
  database: ["database", "server", "table"],
  storage: ["database", "cloud", "drive", "hard"],
  table: ["table", "grid"],
  spreadsheet: ["table", "grid", "document"],
  // Communication
  message: ["chat", "mail", "comment"],
  messaging: ["chat", "comment"],
  chat: ["chat", "comment"],
  conversation: ["chat", "comment"],
  email: ["mail"],
  inbox: ["mail", "inbox", "tray"],
  notification: ["alert", "bell", "badge"],
  notify: ["alert"],
  bell: ["alert"],
  reminder: ["alert", "clock", "calendar"],
  feedback: ["person", "feedback", "chat", "comment", "star"],
  support: ["person", "headset", "chat", "question"],
  help: ["question", "help", "info"],
  faq: ["question", "chat"],
  contact: ["contact", "person", "call", "mail"],
  phone: ["phone", "call"],
  call: ["call", "phone"],
  video: ["video", "camera"],
  meeting: ["video", "people", "calendar", "meeting"],
  announcement: ["megaphone", "alert"],
  broadcast: ["megaphone", "live"],
  social: ["people", "share", "community"],
  comment: ["comment", "chat"],
  // Files and content
  file: ["document", "folder"],
  files: ["document", "folder"],
  doc: ["document"],
  document: ["document"],
  page: ["document", "page"],
  article: ["document", "text", "news"],
  blog: ["document", "text", "news", "edit"],
  news: ["news"],
  note: ["note", "notebook", "notepad"],
  upload: ["arrow", "upload", "up", "cloud"],
  download: ["arrow", "download", "down"],
  attachment: ["attach", "clip"],
  attach: ["attach"],
  image: ["image", "picture"],
  photo: ["image", "camera", "picture"],
  picture: ["image"],
  gallery: ["image", "gallery"],
  media: ["image", "video", "music", "play"],
  library: ["library", "book", "album"],
  archive: ["archive", "box"],
  trash: ["delete", "bin", "recycle"],
  bin: ["delete", "bin"],
  remove: ["delete", "dismiss", "subtract"],
  delete: ["delete", "bin"],
  edit: ["edit", "pen"],
  pencil: ["edit", "pen"],
  write: ["edit", "pen", "compose"],
  compose: ["edit", "compose", "pen"],
  create: ["add", "new"],
  new: ["add", "new"],
  plus: ["add"],
  duplicate: ["copy"],
  clone: ["copy"],
  paste: ["clipboard", "paste"],
  save: ["save"],
  print: ["print"],
  export: ["arrow", "export", "share"],
  import: ["arrow", "import"],
  share: ["share"],
  link: ["link"],
  url: ["link", "globe"],
  code: ["code", "braces"],
  developer: ["code", "developer", "window"],
  api: ["code", "braces", "plug", "connector"],
  integration: ["plug", "connector", "puzzle"],
  plugin: ["puzzle", "plug"],
  extension: ["puzzle"],
  terminal: ["window", "console", "code"],
  bug: ["bug"],
  // Time
  calendar: ["calendar"],
  schedule: ["calendar", "clock"],
  event: ["calendar"],
  date: ["calendar"],
  time: ["clock", "time"],
  history: ["history", "clock", "arrow"],
  recent: ["history", "clock"],
  deadline: ["clock", "calendar", "alert"],
  timer: ["timer", "clock"],
  // Status
  success: ["checkmark", "circle"],
  done: ["checkmark"],
  complete: ["checkmark"],
  check: ["checkmark"],
  ok: ["checkmark"],
  approve: ["checkmark", "thumb", "like"],
  approval: ["checkmark", "approvals"],
  error: ["error", "dismiss", "warning", "alert"],
  fail: ["error", "dismiss"],
  failure: ["error", "dismiss"],
  warning: ["warning", "alert"],
  alert: ["alert", "warning"],
  info: ["info"],
  information: ["info"],
  loading: ["arrow", "sync", "spinner", "hourglass"],
  refresh: ["arrow", "sync", "clockwise"],
  reload: ["arrow", "sync", "clockwise"],
  sync: ["sync", "arrow"],
  block: ["prohibited", "block"],
  ban: ["prohibited"],
  disabled: ["prohibited", "off"],
  hidden: ["eye", "off", "hide"],
  hide: ["eye", "off", "hide"],
  show: ["eye"],
  visible: ["eye"],
  visibility: ["eye"],
  favorite: ["star", "heart"],
  favourite: ["star", "heart"],
  like: ["heart", "thumb", "like"],
  love: ["heart"],
  rating: ["star"],
  review: ["star", "comment"],
  bookmark: ["bookmark"],
  saved: ["bookmark", "save"],
  pin: ["pin"],
  // Search and filters
  search: ["search"],
  find: ["search"],
  magnify: ["search", "zoom"],
  filter: ["filter"],
  sort: ["sort", "arrow"],
  zoom: ["zoom", "search"],
  // Places and things
  location: ["location", "map", "pin"],
  map: ["map", "location"],
  address: ["location", "map"],
  place: ["location"],
  globe: ["globe", "earth"],
  world: ["globe", "earth"],
  language: ["translate", "globe", "local", "language"],
  translation: ["translate"],
  company: ["building", "organization"],
  organization: ["building", "organization", "people"],
  office: ["building", "desk", "briefcase"],
  business: ["briefcase", "building"],
  work: ["briefcase"],
  job: ["briefcase"],
  shipping: ["vehicle", "truck", "box"],
  delivery: ["vehicle", "truck", "box"],
  package: ["box"],
  product: ["box", "cube", "tag"],
  inventory: ["box", "archive", "stack"],
  education: ["hat", "graduation", "book"],
  school: ["hat", "graduation", "book"],
  learn: ["hat", "graduation", "book", "lightbulb"],
  learning: ["hat", "graduation", "book"],
  course: ["hat", "graduation", "book"],
  health: ["heart", "pulse", "medical"],
  medical: ["medical", "stethoscope", "pill"],
  weather: ["weather"],
  // AI
  ai: ["sparkle", "bot", "brain", "copilot"],
  assistant: ["bot", "sparkle", "person"],
  robot: ["bot"],
  magic: ["sparkle", "wand"],
  generate: ["sparkle", "wand"],
  // Devices and system
  computer: ["desktop", "laptop", "pc"],
  mobile: ["phone", "mobile"],
  device: ["phone", "laptop", "desktop", "device"],
  cloud: ["cloud"],
  server: ["server", "database"],
  network: ["network", "wifi", "globe"],
  internet: ["globe", "wifi"],
  wifi: ["wifi"],
  power: ["power", "battery", "plug"],
  battery: ["battery"],
  volume: ["speaker"],
  sound: ["speaker", "sound"],
  mute: ["speaker", "mic", "off"],
  microphone: ["mic"],
  music: ["music"],
  audio: ["speaker", "music", "headphones"],
  camera: ["camera"],
  screen: ["desktop", "screen", "window"],
  fullscreen: ["full", "screen", "maximize", "arrow"],
  window: ["window"],
  dark: ["dark", "moon", "theme"],
  light: ["sunny", "lightbulb"],
  mode: ["dark", "theme"],
  night: ["moon", "night"],
  // Layout and editing
  layout: ["layout", "grid", "board"],
  grid: ["grid", "table"],
  list: ["list", "bullet"],
  card: ["card"],
  view: ["eye", "view", "grid"],
  drag: ["re", "order", "dot", "arrow", "move"],
  move: ["arrow", "move"],
  resize: ["resize", "arrow"],
  text: ["text"],
  font: ["text", "font"],
  bold: ["text", "bold"],
  italic: ["text", "italic"],
  align: ["align", "text"],
  undo: ["arrow", "undo"],
  redo: ["arrow", "redo"],
  // Misc
  gift: ["gift"],
  reward: ["gift", "trophy", "star", "ribbon"],
  achievement: ["trophy", "ribbon", "badge"],
  award: ["trophy", "ribbon"],
  goal: ["target", "flag", "trophy"],
  target: ["target"],
  launch: ["rocket", "open"],
  rocket: ["rocket"],
  idea: ["lightbulb"],
  tip: ["lightbulb"],
  flag: ["flag"],
  tag: ["tag"],
  label: ["tag"],
  category: ["tag", "folder", "grid"],
  question: ["question"],
  lock: ["lock"],
  key: ["key"],
  shield: ["shield"],
};
